-- CREATE DATABASE chatbot_db;
-- USE chatbot_db;
-- Create the table for questions and answers
-- CREATE TABLE qa (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   question VARCHAR(255) NOT NULL,
--   answer VARCHAR(255) NOT NULL
-- );
-- desc qa

-- INSERT INTO qa (question, answer) VALUES
--   ('What is your name?', 'My name is ChatBot.'),
--   ('How are you?', 'I am fine, thank you.'),
--   ('What is the weather like today?', 'I am sorry, I do not have access to real-time weather information.'),
--   ('Can you help me with programming?', 'Of course! I can assist you with programming questions.'),
--   ('What is the capital of France?', 'The capital of France is Paris.');
INSERT INTO qa (question, answer) VALUES
	('Are you a robot?', 'Yes I am a robot, but I am a good one. Let me prove it. How can I help you?'),
    ('How do you function?', 'I am a Java-based chat bot that can answer questions based on a predefined set of questions and answers stored in a MySQL database. If a question is not available in the database, it can perform a Google search and display the results.'),
    ('How does a chatbot work?', 'A chatbot uses algorithms and natural language processing techniques to understand and respond to user input.'),
	('Are you human?', 'No, I am an artificial intelligence language model.'),
		('What is the weather like today?', 'I am sorry, I do not have access to real-time data. You can check a weather website or app for the latest information.'),
	('What is the capital of France?', 'The capital of France is Paris.'),
	('Who is the current President of the United States?', 'Joe Biden'),
	('How tall is Mount Everest?', 'Mount Everest is approximately 8,848 meters (29,029 feet) tall.'),
	('What is the meaning of life?', 'The meaning of life can vary for different individuals and philosophical beliefs. It is  a question that has been pondered by many throughout history.'),
	('Tell me a joke.', 'Why do not scientists trust atoms? Because they make up everything!'),
	('What is the square root of 144?', 'The square root of 144 is 12.'),
	('Who painted the Mona Lisa?', 'The Mona Lisa was painted by Leonardo da Vinci.'),
	('What is the largest planet in our solar system?', 'The largest planet in our solar system is Jupiter.'),
	('How many continents are there?', 'There are seven continents: Africa, Antarctica, Asia, Europe, North America, Australia, and South America.'),
	('What is the speed of light?', 'The speed of light in a vacuum is approximately 299,792 kilometers per second (186,282 miles per second).'),
	('Who wrote the play "Romeo and Juliet"?', 'The play "Romeo and Juliet" was written by William Shakespeare.'),
	('What is the chemical symbol for gold?', 'The chemical symbol for gold is Au.'),
	('What is the formula for water?', 'The chemical formula for water is H2O.'),
	('What is the tallest building in the world?', 'As of my knowledge cutoff in September 2021, the tallest building in the world is the Burj Khalifa in Dubai, United Arab Emirates.'),
	('What is the currency of Japan?', 'The currency of Japan is the Japanese yen.'),
	('What is the national animal of Australia?', 'The national animal of Australia is the kangaroo.'),
	('Who discovered electricity?', 'Electricity was not discovered by a single individual, but its study and understanding have been attributed to various scientists such as Benjamin Franklin, Thomas Edison, and Nikola Tesla.'),
	('What is the chemical symbol for oxygen?', 'The chemical symbol for oxygen is O.'),
	('How many players are there in a basketball team?', 'In a basketball game, each team typically has five players on the court.'),
	('Who was the first person to walk on the moon?', 'The first person to walk on the moon was Neil Armstrong.'),
	('What is the largest ocean on Earth?', 'The largest ocean on Earth is the Pacific Ocean.'),
	('What is the meaning of the word "serendipity"?', 'Serendipity means the occurrence of fortunate events by chance.'),
	('Who is the author of "Pride and Prejudice"?', 'The author of "Pride and Prejudice" is Jane Austen.'),
	('What is the chemical symbol for carbon?', 'The chemical symbol for carbon is C.'),
	('What is the boiling point of water?', 'Water boils at 100 degrees Celsius (212 degrees Fahrenheit) at sea level under normal atmospheric conditions.'),
	('What is the largest mammal on Earth?', 'The blue whale is the largest mammal on Earth.'),
	('Who painted the famous artwork "Starry Night"?', 'The famous artwork "Starry Night" was painted by Vincent van Gogh.'),
	('What is the national flower of India?', 'The national flower of India is the lotus.'),
	('How many planets are there in our solar system?', 'There are eight planets in our solar system: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.'),
	('Who is the Greek god of thunder?', 'The Greek god of thunder is Zeus.'),
	('What is the chemical symbol for sodium?', 'The chemical symbol for sodium is Na.'),
	('What is the square root of 25?', 'The square root of 25 is 5.'),
	('Who wrote the novel "1984"?', 'The novel "1984" was written by George Orwell.'),
	('What is the largest bird in the world?', 'The largest bird in the world is the ostrich.'),
	('What is the formula for calculating the area of a circle?', 'The formula for calculating the area of a circle is A = πr², where A represents the area and r represents the radius of the circle.'),
	('Who discovered the theory of relativity?', 'The theory of relativity was developed by Albert Einstein.'),
	('What is the official language of Brazil?', 'The official language of Brazil is Portuguese.'),
	('What is the boiling point of nitrogen?', 'Nitrogen boils at approximately -196 degrees Celsius (-321 degrees Fahrenheit).'),
	('What is the largest desert in the world?', 'The largest desert in the world is the Sahara Desert in Africa.'),
	('Who painted the ceiling of the Sistine Chapel?', 'The ceiling of the Sistine Chapel was painted by Michelangelo.'),
	('What is the chemical symbol for iron?', 'The chemical symbol for iron is Fe.'),
	('What is the atomic number of hydrogen?', 'The atomic number of hydrogen is 1.'),
	('What is the national animal of Canada?', 'The national animal of Canada is the beaver.'),
	('How many sides does a hexagon have?', 'A hexagon has six sides.'),
	('Who wrote the play "Hamlet"?', 'The play "Hamlet" was written by William Shakespeare.'),
	('What is the chemical symbol for silver?', 'The chemical symbol for silver is Ag.'),
	('What is the freezing point of water?', 'Water freezes at 0 degrees Celsius (32 degrees Fahrenheit) at sea level under normal atmospheric conditions.'),
	('Who discovered penicillin?', 'Penicillin was discovered by Alexander Fleming.'),
	('What is the capital of Brazil?', 'The capital of Brazil is Brasília.'),
	('What is the national flower of Japan?', 'The national flower of Japan is the cherry blossom.'),
	('What is the chemical symbol for helium?', 'The chemical symbol for helium is He.'),
	('What is the largest city in the United States?', 'The largest city in the United States is New York City.'),
	('Who is the author of "To Kill a Mockingbird"?', 'The author of "To Kill a Mockingbird" is Harper Lee.'),
	('What is the chemical formula for glucose?', 'The chemical formula for glucose is C6H12O6.'),
	('Who painted the famous artwork "The Last Supper"?', 'The famous artwork "The Last Supper" was painted by Leonardo da Vinci.'),
	('What is the national animal of China?', 'The national animal of China is the giant panda.'),
	('What is the boiling point of ethanol?', 'Ethanol boils at approximately 78 degrees Celsius (173 degrees Fahrenheit).'),
	('What is the largest waterfall in the world?', 'The largest waterfall in the world is Victoria Falls, located on the border of Zambia and Zimbabwe in Africa.'),
	('Who wrote the novel "Moby-Dick"?', 'The novel "Moby-Dick" was written by Herman Melville.'),
	('What is the chemical symbol for potassium?', 'The chemical symbol for potassium is K.'),
	('What is the atomic number of oxygen?', 'The atomic number of oxygen is 8.'),
	('What is the national animal of Russia?', 'The national animal of Russia is the Russian bear.'),
	('How many sides does a pentagon have?', 'A pentagon has five sides.'),
	('Who wrote the play "Macbeth"?', 'The play "Macbeth" was written by William Shakespeare.'),
	('What is the chemical symbol for copper?', 'The chemical symbol for copper is Cu.'),
	('What is the atomic number of carbon?', 'The atomic number of carbon is 6.'),
	('What is the boiling point of mercury?', 'Mercury boils at approximately 356 degrees Celsius (673 degrees Fahrenheit).'),
	('Who discovered gravity?', 'Gravity was not discovered by a single individual, but its study and understanding have been attributed to scientists such as Sir Isaac Newton.'),
	('What is the capital of Australia?', 'The capital of Australia is Canberra.'),
	('What is the national flower of England?', 'The national flower of England is the rose.'),
	('What is the chemical symbol for nitrogen?', 'The chemical symbol for nitrogen is N.'),
	('What is the largest lake in the world?', 'The largest lake in the world by surface area is the Caspian Sea.'),
	('Who is the author of "The Great Gatsby"?', 'The author of "The Great Gatsby" is F. Scott Fitzgerald.'),
	('What is the chemical formula for carbon dioxide?', 'The chemical formula for carbon dioxide is CO2.'),
	('Who painted the famous artwork "The Starry Night"?', 'The famous artwork "The Starry Night" was painted by Vincent van Gogh.'),
	('What is the national animal of Germany?', 'Germany does not have a designated national animal.'),
	('What is the boiling point of gold?', 'Gold has a very high boiling point of approximately 2,800 degrees Celsius (5,100 degrees Fahrenheit).'),
	('What is the largest island in the world?', 'The largest island in the world is Greenland.'),
	('Who wrote the novel "The Catcher in the Rye"?', 'The novel "The Catcher in the Rye" was written by J.D. Salinger.'),
	('What is the chemical symbol for calcium?', 'The chemical symbol for calcium is Ca.'),
	('What is the atomic number of helium?', 'The atomic number of helium is 2.'),
	('What is the national animal of South Africa?', 'The national animal of South Africa is the springbok.'),
	('How many sides does an octagon have?', 'An octagon has eight sides.'),
	('Who wrote the play "A Midsummer Nights Dream"?', 'The play "A Midsummer Nights Dream" was written by William Shakespeare.'),
	('What is the chemical symbol for zinc?', 'The chemical symbol for zinc is Zn.'),
	('What is the atomic number of gold?', 'The atomic number of gold is 79.'),
	('What is the boiling point of water in Kelvin?', 'The boiling point of water in Kelvin is approximately 373 Kelvin.'),
	('Who discovered the law of gravity?', 'The law of gravity was developed by Sir Isaac Newton.'),
	('What is the capital of Canada?', 'The capital of Canada is Ottawa.'),
	('What is the national flower of France?', 'The national flower of France is the iris.'),
	('What is the chemical symbol for helium?', 'The chemical symbol for helium is He.'),
	('What is the largest river in the world?', 'The largest river in the world by volume is the Amazon River in South America.'),
	('Who is the author of "The Hobbit"?', 'The author of "The Hobbit" is J.R.R. Tolkien.');
		
